apiVersion: v1
kind: ReplicationController
metadata:
  name: mavenwebapprc
spec:
  replicas: 2
  selector:
    app: mavenwebapp
  template:
    metadata:
      name: mavenwebapppod
      labels:
        app: mavenwebapp
    spec:
      containers:
      - image: rani12345/maven-web-app
        name: mavenwebapp
        ports:
        - containerPort: 8080
---
#Service
apiVersion: v1
kind: Service
metadata:
  name: mavenwebapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: mavenwebapp
    
    
